### PR TITLE
footer-cta and footer section: initial commit

### PR DESCRIPTION
**Pull request by misspee007**
Kindly review and let me know if I need to change anything, I'm particularly concerned about the alignment.

### CODE REVIEW

**Comment by misspee007** [comment]
image

**Review by biggaji — CHANGES_REQUESTED** [review]
Welldone precious, the layout is okay, you just need to fix the white spaces, they are to much, then also cross check the texts and remove the dhd icon.

**Comment by misspee007** [comment]
How about now?

image

**Review by biggaji — APPROVED** [review]
It is good. welldone.

**Pull request merged**
